apiVersion: v1
kind: Secret
metadata:
  name: api-key-server-credentials
  namespace: mcp-test
  labels:
    mcp.kuadrant.io/secret: "true"  # required label for secrets managed by the controller
type: Opaque
stringData:
  token: "Bearer test-api-key-secret-token"
