apiVersion: v1
kind: Secret
metadata:
  name: oidc-server-credentials
  namespace: mcp-test
  labels:
    mcp.kuadrant.io/secret: "true"  # required label for secrets managed by the controller
type: Opaque
stringData:
  admin_token: "APIKEY test-api-key-secret-token-for-oidc-server"
